@startuml
title Example

Frontend -> Middletier: GET /posts

Middletier -> Backend: GET [[http://example.com /comments]]
Backend -> Service: comments
Service --> Backend: return(comments)
Backend --> Middletier: return(comments)

alt links not provided
  Middletier -> Backend: GET [[http://example.com /thumbnails]]
  Backend --> Middletier: return(thumbnails)
  Middletier -> Backend: GET [[http://example.com /likes]]
  Backend --> Middletier: return(likes)
else  links provided
    Middletier -> Backend: POST [[http://example.com /links]]
    Backend --> Middletier: return(links)
end

Middletier --> Frontend: return(posts)
@enduml
